addressbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import contacts.views

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'addressbook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', contacts.views.ListContactView.as_view(),
        name='contacts-list',),
    url(r'^new$', contacts.views.CreateContactView.as_view(),
        name='contacts-new',),
    url(r'^edit/(?P<pk>\d+)/$', contacts.views.UpdateContactView.as_view(),
        name='contacts-edit',),
    url(r'^delete/(?P<pk>\d+)/$', contacts.views.DeleteContactView.as_view(),
        name='contacts-delete',),
    url(r'^(?P<pk>\d+)/$', contacts.views.ContactView.as_view(),
        name='contacts-view',),
    url(r'^edit/(?P<pk>\d+)/addresses$', contacts.views.EditContactAddressView.as_view(),
        name='contacts-edit-addresses',),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
)

urlpatterns += staticfiles_urlpatterns()

contacts/urls.py
from django.conf.urls import patterns, include, url
from contacts import views

urlpatterns = patterns('',
		
)

contacts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
# Create your models here.

class Contact(models.Model):

    first_name = models.CharField(
        max_length=255,
    )
    last_name = models.CharField(
        max_length=255,

    )

    email = models.EmailField()

    owner = models.ForeignKey(User)

    def __str__(self):

        return ' '.join([
            self.first_name,
            self.last_name,
        ])

    def get_absolute_url(self):

        return reverse('contacts-view', kwargs={'pk': self.id})

class Address(models.Model):

    contact = models.ForeignKey(Contact)
    address_type = models.CharField(
        max_length=10,
    )

    address = models.CharField(
        max_length=255,
    )
    city = models.CharField(
        max_length=255,
    )
    state = models.CharField(
        max_length=2,
    )
    postal_code = models.CharField(
        max_length=20,
    )

    class Meta:
        unique_together = ('contact', 'address_type',)

contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory
from contacts.models import Contact
from contacts.models import (
    Contact,
    Address,
)

class ContactForm(forms.ModelForm):

    confirm_email = forms.EmailField(
        #Confirm email
        required=True,
    )

    class Meta:
        model = Contact

    def __init__(self, *args, **kwargs):

        if kwargs.get('instance'):
            email = kwargs['instance'].email
            kwargs.setdefault('initial', {})['confirm_email'] = email

        return super(ContactForm, self).__init__(*args, **kwargs)

    def clean(self): # validation method

        if (self.cleaned_data.get('email') !=
            self.cleaned_data.get('confirm_email')):

            raise ValidationError(
                "Email addresses must match."
            )

        return self.cleaned_data
        
# inlineformset_factory creates a Class from a parent model (Contact)
# to a child model (Address)
ContactAddressFormSet = inlineformset_factory(
    Contact,
    Address,
)

contacts/views.py
from django.http import HttpResponse
from django.views.generic import View
from django.shortcuts import render
from django.views.generic import ListView
from contacts.models import Contact
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.core.urlresolvers import reverse
from django.views.generic import DeleteView
from django.views.generic import DetailView
import forms
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
def hello_world(request):
    return HttpResponse("Hello, World")

class LoggedInMixin(object): # class mixin that ensures the user is logged in

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)

class MyView(View): #class based views

    def get(self, request, *args, **kwargs):
        return HttpResponse("Hello, World")

class ListContactView(LoggedInMixin, ListView): #a view that presents a list of contacts in the database

    model = Contact
    template_name = 'contact_list.html'

    def get_queryset(self):

        return Contact.objects.filter(owner=self.request.user)

class CreateContactView(CreateView): #a view for adding a new contact

    model = Contact
    template_name = 'edit_contact.html'
    form_class = forms.ContactForm

    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):

        context = super(CreateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-new')

        return context

class UpdateContactView(UpdateView): #view for editing contacts

    model = Contact
    template_name = 'edit_contact.html'
    form_class = forms.ContactForm

    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):

        context = super(UpdateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-edit',
                                    kwargs={'pk': self.get_object().id})

        return context

class DeleteContactView(DeleteView): #view for deleting contact

    model = Contact
    template_name = 'delete_contact.html'

    def get_success_url(self):
        return reverse('contacts-list')

class ContactView(DetailView): # view for details for our contacts, this will show the details of the contacts

    model = Contact
    template_name = 'contact.html'

class EditContactAddressView(UpdateView): #view for edit addresses html

    model = Contact
    template_name = 'edit_addresses.html'
    form_class = forms.ContactAddressFormSet

    def get_success_url(self):

        # redirect to the Contact view.
        return self.get_object().get_absolute_url()

contacts/templates/base.html
{% load staticfiles %}

<html>
	<head>
		<!--<link href="{% static 'bootstrap/css/bootstrap.min.css' %}"rel="stylesheet" media="screen">-->
		<link href="{% static 'bootstrap/css/bootstrap.css'%}" rel="stylesheet">
		<style type="text/css">
		body {
       		padding-top: 40px;
        	padding-bottom: 40px;
        	background-color: #f5f5f5;
      		}

      .form-signin {
        	max-width: 300px;
        	padding: 19px 29px 29px;
        	margin: 0 auto 20px;
        	background-color: #fff;
        	border: 1px solid #e5e5e5;
        		-webkit-border-radius: 5px;
           		-moz-border-radius: 5px;
                	border-radius: 5px;
        		-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           		-moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                	box-shadow: 0 1px 2px rgba(0,0,0,.05);
      				}
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        	margin-bottom: 10px;
      						}
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        	font-size: 16px;
        	height: auto;
        	margin-bottom: 15px;
        	padding: 7px 9px;
     									}
		</style>
		
    	<!--<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-fluid-adj.css' %}" >
    	<link rel="stylesheet" media="screen" href="{% static 'bootstrap/css/bootstrap.min.css'% }" >-->
    	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-responsive.css' %}">
	</head>

	<body>
   			<div class="container">
   				<form class="form-signin">
						<h2 class="form-signin-heading">Anonymous Login </h2>
       					{{ user }}
       					{% if user.is_anonymous %}
       					<a class="brand" href="{% url 'django.contrib.auth.views.login' %}">login</a>
       					{% else %} 
       					<a class="brand" href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
       					{% endif%}
       			</form>
			</div>

		<!--<div>
			{{ user }}
			{% if user.is_anonymous %}
			<a href="{% url 'django.contrib.auth.views.login' %}">login</a>
			{% else %}
			<a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
			{% endif %}
		</div> -->

    {% block content %}
    {% endblock %}

    <script src="{% static 'bootstrap/js/jquery.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!--<script src="{% static 'bootstrap/js/jquery-2.0.3.min.js' %}"></script>
  </body>
</html>

contacts/templates/contact.html
{% extends "base.html" %}

{% block content %}

<div class="container">
	<form class="form-signin" >
		<h1>{{ contact }}</h1>

		<p>Email: {{ contact.email }}</p>

		<ul>
				{% for address in contact.address_set.all %}
   			<li>{{ address.address }}<br/>
       			{{ address.city }} {{ address.state }}<br/>
       			{{ address.postal_code }}
   			</li>
				{% endfor %}
		</ul>

		<a href="{% url "contacts-list" %}">back to list</a>
	</form>
</div>
{% endblock %}

contacts/templates/contact_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<form class="form-signin">
		<h1>Contacts</h1>

			<ul>
				{% for contact in object_list %}
					<li class="contact">
					<a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
					(<a href="{% url "contacts-edit" pk=contact.id %}">edit</a>)
					</li>
				{% endfor %} 
			</ul>
	
		<a href="{% url "contacts-new" %}">Add contact</a>
	</form>
</div>

{% endblock %}

contacts/templates/delete_contact.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<form class="form-signin" action="{% url "contacts-delete" pk=contact.id %}" method="POST">

		<h1>Delete Contact</h1>

		<p>Are you sure you want to delete the contact {{ contact }}?</p>

		<!--<form action="{% url "contacts-delete" pk=contact.id %}" method="POST"> this form has been commented out because it is being used above and it has the class forn signin so that it cd style the form as well-->
		{% csrf_token %}

		<input type="submit" value="Yes, delete." />
		<a href="{% url "contacts-list" %}">No, cancel.</a>
</form>

{% endblock %}

contacts/templates/edit_addresses.html
{% extends "base.html" %}

{% block content %}

<div class="container">
	<!--<form class="form-signin">-->
	<form class="form-signin" action="{% url "contacts-edit-addresses" pk=contact.id %}" method="POST">

		<h1>Edit Addresses</h1>		

		<p>Editing addresses for {{ contact }}</p>

			<!--<form class="form-signin" action="{% url "contacts-edit-addresses" pk=contact.id %}" method="POST>This form was shifted up instead-->
    		{% csrf_token %}
    		{{ form.management_form }} <!--This is a set of hidden fields that provide some accounting information to django-->
    		{% for address_form in form %}

        	<ul>
        		{{ address_form.as_ul }}
        	</ul>

    		{% endfor %}

    		<input type="submit" value="Save" />
		<!--</form>-->
		<p>
		<a href="{% url "contacts-edit" pk=contact.id %}">back to Edit</a>
		</p>
	</form>
</div>
{% endblock %}

contacts/templates/edit_contact.html
{% extends "base.html" %}

{% block content %}
<div class="container" >
  <form class="form-signin" action="{{ action }}" method="POST" >
        {% if contact.id %}
          <h1>Edit Contact</h1>
        {% else %}
          <h1>Add Contact</h1>
        {% endif %}

    <!--<form class="container" action="{{ action }}" method="POST">-->
          {% csrf_token %}
          {% if form.non_field_errors %}
          <ul>
            {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
            {% endif %}
            {% for field in form %}
      <div id="{{ field.auto_id }}_container">
          {{ field.help_text }}
            <div>
              {{ field.label_tag }} {{ field }}
            </div>
          <div id="{{ field.auto_id }}_errors">
            {{ field.errors }}
          </div>
      </div>
          {% endfor %}
        <p>
        <input id="save_contact" type="submit" value="Save" />
        </p>
    <!--</form>-->

      {% if contact.id %}
      <p>
        <a href="{% url "contacts-edit-addresses" pk=contact.id %}">
      Edit Addresses
        </a>
      </p>

      <p><a href="{% url "contacts-delete" pk=contact.id %}">Delete</a></p>
      {% endif %}

      <a href="{% url "contacts-list" %}">back to list</a>
  </form>
</div>

{% endblock %}